SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';
SELECT name FROM sqlite_master WHERE type='view';
SELECT * FROM VISTA_TIPOS_FILTRO;
DELETE FROM TIPOS_FILTRO;
SELECT * FROM sqlite_sequence;

-- Obtiene la secuencia de inserción de 
SELECT 
    'INSERT INTO TIPOS_FILTRO (TIPO_FILTRO, OBSERVACIONES) VALUES (''' || REPLACE(TIPO_FILTRO, '''', '''''') || ''', ''' ||
    REPLACE(OBSERVACIONES, '''', '''''') || ''');'
FROM TIPOS_FILTRO;

VACUUM;

CREATE TABLE IF NOT EXISTS INCIDENCIAS (
    ID_INCIDENCIA      INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ACUARIO         INTEGER,
    FECHA              INTEGER,
    ID_CATEGORIA       INTEGER,
    ID_SUBCATEGORIA    INTEGER,
    DESCRIPCION        TEXT(128),
    RESUELTA           INTEGER DEFAULT 0,  -- 0 = No, 1 = Sí
    FECHA_RESOLUCION   INTEGER,
    OBSERVACIONES      TEXT,
    CONSTRAINT FK_INCIDENCIA_ACUARIO FOREIGN KEY (ID_ACUARIO) 
        REFERENCES ACUARIOS(ID_ACUARIO)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT CATEGORIA_INCIDENCIA FOREIGN KEY (ID_CATEGORIA) 
        REFERENCES ACUARIOS(ID_CATEGORIA)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT CATEGORIA_INCIDENCIA FOREIGN KEY (ID_CATEGORIA) 
        REFERENCES ACUARIOS(ID_CATEGORIA)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE CATEGORIA_INCIDENCIA (
    ID_CATEGORIA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_CATEGORIA TEX(64),
    DESCRIPCION TEXT,
    CONSTRAINT IX_CATEGORIA UNIQUE (NOMBRE_CATEGORIA)
);

CREATE TABLE SUBCATEGORIA_INCIDENCIA (
    ID_SUBCATEGORIA INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_CATEGORIA INTEGER NOT NULL,
    NOMBRE_SUBCATEGORIA TEXT(64) NOT NULL,
    DESCRIPCION TEXT,
    CONSTRAINT IX_SUBCATEGORIA UNIQUE (NOMBRE_SUBCATEGORIA)
);

CREATE VIEW VISTA_TIPOS_ACUARIO AS
    SELECT   ID_TIPO AS ID,
             ROW_NUMBER() OVER(ORDER BY TIPO_ACUARIO, SUBTIPO_ACUARIO) AS NUM,
             TIPO_ACUARIO AS TIPO,
             SUBTIPO_ACUARIO AS SUBTIPÒ,
             DESCRIPCION
    FROM     TIPOS_ACUARIO;
