CREATE TABLE ACUARIO_HISTORICO (
    ID_HISTORICO  INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ACUARIO    INTEGER CONSTRAINT FK_ACUARIOHISTORICO_ACUARIO
                    REFERENCES ACUARIOS (ID_ACUARIO) ON DELETE SET NULL
                                                     ON UPDATE CASCADE,
    FECHA         INTEGER,
    OBSERVACIONES TEXT
);

CREATE TABLE ACUARIOS (
    ID_ACUARIO     INTEGER   PRIMARY KEY AUTOINCREMENT,
    ID_MARCA       INTEGER   CONSTRAINT FK_ACUARIO_MARCACOMERCIAL
                    REFERENCES MARCAS_COMERCIALES (ID_MARCA) ON DELETE SET NULL
                                                              ON UPDATE CASCADE,
    MODELO         TEXT (64),
    ANCHURA        INTEGER,
    PROFUNDIDAD    INTEGER,
    ALTURA         INTEGER,
    GROSOR_CRISTAL INTEGER,
    VOLUMEN_TANQUE INTEGER,
    ID_MATERIAL    INTEGER   CONSTRAINT FK_ACUARIO_MATERIALURNA
                    REFERENCES MATERIALES_URNA (ID_MATERIAL) ON DELETE SET NULL
                                                          ON UPDATE SET DEFAULT,
    DESCRIPCION    TEXT
);

CREATE TABLE CATEGORIAS_ACUARIO (
    ID_CATEGORIA_ACUARIO INTEGER   PRIMARY KEY AUTOINCREMENT,
    CATEGORIA_ACUARIO    TEXT (32) CONSTRAINT IX_CATEGORIA_aCUARIO UNIQUE,
    OBSERVACIONES        TEXT
);

CREATE TABLE CATEGORIAS_EQUIPAMIENTO (
    ID_CATEGORIA_EQUIPAMIENTO INTEGER   PRIMARY KEY AUTOINCREMENT,
    CATEGORIA_EQUIPAMIENTO    TEXT (32),
    OBSERVACIONES             TEXT
);

CREATE TABLE CATEGORIAS_INCIDENCIA (
    ID_CATEGORIA     INTEGER  PRIMARY KEY AUTOINCREMENT,
    NOMBRE_CATEGORIA TEX (32),
    OBSERVACIONES    TEXT,
    CONSTRAINT IX_CATEGORIA UNIQUE (
        NOMBRE_CATEGORIA
    )
);

CREATE TABLE CATEGORIAS_PRODUCTO (
    ID_CATEGORIA_PRODUCTO INTEGER PRIMARY KEY AUTOINCREMENT,
    CATEGORIA_PRODUCTO    TEXT (25) UNIQUE,
    DESCRIPCION           TEXT
);

CREATE TABLE CICLADOS (
    ID_CICLADO          INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PROYECTO_ACUARIO INTEGER CONSTRAINT FK_CICLADO_PROYEECTOACUARIO
                         REFERENCES PROYECTOS_ACUARIOS (ID_PROYECTO_ACUARIO)
                         ON DELETE SET NULL
                         ON UPDATE CASCADE,
    FECHA_INICIO        INTEGER,
    FECHA_CIERRE        INTEGER,
    OBSERVACIONES       TEXT
);

CREATE TABLE COMERCIOS (
    ID_COMERCIO   INTEGER    PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT,
    COMERCIO      TEXT (55)  UNIQUE
                             NOT NULL,
    DIRECCION     TEXT (125),
    COD_POSTAL    TEXT (15),
    POBLACION     TEXT (25),
    PROVINCIA     TEXT (25),
    ID_PAIS       INTEGER,
    OBSERVACIONES TEXT
);

CREATE TABLE COMPRAS (
    ID_COMPRA    INTEGER   PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT,
    FECHA_COMPRA INTEGER,
    NUM_FACRURA  TEXT (25) UNIQUE,
    ID_COMERCIO  INTEGER   CONSTRAINT FK_COMPRA_COMERCIO
                    REFERENCES COMERCIOS (ID_COMERCIO) ON DELETE CASCADE
                                                       ON UPDATE CASCADE,
    OBERVACIONES TEXT
);

CREATE TABLE DETALLES_CICLADO (
    ID_DETALLE_CICLADO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_CICLADO         INTEGER CONSTRAINT FK_DETALLECICLADO_CICLADO
                        REFERENCES CICLADOS (ID_CICLADO) ON DELETE SET NULL
                                                         ON UPDATE CASCADE,
    FECHA              INTEGER,
    OBSERVACIONES      TEXT
);

CREATE TABLE DETALLES_COMPRA (
    ID_DETALLE_FACTURA    INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT,
    ID_COMPRA             INTEGER     CONSTRAINT FK_FACTURA_DETALLECOMPRA
                             REFERENCES COMPRAS (ID_COMPRA) ON DELETE CASCADE
                                                            ON UPDATE CASCADE,
    ID_MARCA              INTEGER     CONSTRAINT FK_DETALLECOMPRA_MARCACOMERCIAL
                    REFERENCES MARCAS_COMERCIALES (ID_MARCA) ON DELETE CASCADE
                                                             ON UPDATE CASCADE,
    MODELO                TEXT (255)  NOT NULL,
    ID_CATEGORIA_PRODUCTO INTEGER
        CONSTRAINT FK_CATEGORIAPRODUCTO_DETALLESCOMPRA
        REFERENCES CATEGORIAS_PRODUCTO (ID_CATEGORIA_PRODUCTO) ON DELETE SET NULL
                                                               ON UPDATE CASCADE,
    PRECIO                REAL (8, 2),
    DESCRIPCION           TEXT
);

CREATE TABLE DETALLES_INCIDENCIA (
    ID_DETALLE_INCIDENCIA INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_INCIDENCIA         INTEGER CONSTRAINT FK_DETALLESINCIDENCIA_INCIDENCIA
            REFERENCES INCIDENCIAS (ID_INCIDENCIA) ON DELETE CASCADE
                                                   ON UPDATE CASCADE,
    ID_EQUIPO             INTEGER,
    FECHA_DETALLE         INTEGER,
    OBSERVACIONES         TEXT
);

CREATE TABLE DETALLES_PLAN_MANTENIMIENTO (
    ID_DETALLE_PLAN_MANTENIMIENTO INTEGER   PRIMARY KEY AUTOINCREMENT,
    ID_PLAN_MANTENIMIENTO         INTEGER
      CONSTRAINT FK_DETALLESMANTENIMIENTO_PLAN_MANTENIMIENTO
      REFERENCES PLANES_MANTENIMIENTO (ID_PLAN_MANTENIMIENTO) ON DELETE CASCADE
                                                              ON UPDATE CASCADE,
    NOMBRE                        TEXT (64),
    ID_TIPO_MANTENIMIENTO         INTEGER
      REFERENCES TIPO_MANTENIMIENTO (ID_TIPO_MANTENIMIENTO) ON DELETE CASCADE
                                                            ON UPDATE CASCADE,
    ID_SUBTIPO_MANTENIMIENTO      INTEGER,
    PERIODO                       INTEGER,
    ID_PERIODICIDAD               INTEGER
      CONSTRAINT FK_DETALLESPLANMANTENIMIENTO_PERIODICIDADES
      REFERENCES PERIODICIDADES (ID_PERIODICIDAD) ON DELETE SET NULL
                                                  ON UPDATE CASCADE,
    DESCRIPCION                   TEXT
);

CREATE TABLE DIFICULTADES_PLANTAS (
    ID_DIFICULTAD INTEGER PRIMARY KEY AUTOINCREMENT,
    DIFICULTAD    TEXT    UNIQUE
                          NOT NULL,
    DESCRIPCION   TEXT
);

CREATE TABLE EQUIPAMIENTOS (
    ID_EQUIPAMIENTO           INTEGER   PRIMARY KEY AUTOINCREMENT,
    ID_PROYECTO_ACUARIO       INTEGER
      CONSTRAINT FK_EQUIPAMIENTO_PROYECTOACUARIO
      REFERENCES PROYECTOS_ACUARIOS (ID_PROYECTO_ACUARIO) ON DELETE SET NULL
                                                          ON UPDATE CASCADE,
    ID_CATEGORIA_EQUIPAMIENTO INTEGER
      CONSTRAINT FK_EQUIPAMIENTO_CATEGORIAEQUIPAMIENTO
      REFERENCES CATEGORIAS_EQUIPAMIENTO (ID_CATEGORIA_EQUIPAMIENTO)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    ID_MARCA                  INTEGER
      CONSTRAINT FK_EQUIPAMIENTO_MARCACOMERCIAL
      REFERENCES MARCAS_COMERCIALES (ID_MARCA) ON DELETE SET NULL
                                               ON UPDATE CASCADE,
    MODELO                    TEXT (32),
    DESCRIPCION               TEXT
);

CREATE TABLE ESPECIES_ANIMALES (
    ID_ESPECIE          INTEGER   PRIMARY KEY AUTOINCREMENT,
    REINO               TEXT (32),
    FILO                TEXT (32),
    CLASE               TEXT (32),
    ORDEN               TEXT (32),
    FAMILIA             TEXT (32),
    GENERO              TEXT (32),
    ESPECIE             TEXT (32),
    NOMBRE_CIENTIFICO
        [TEXT ]   GENERATED ALWAYS AS (GENERO || ' ' || ESPECIE) STORED UNIQUE,
    NOMBRE_COMUN        TEXT (32),
    ID_GRUPO_TAXONOMICO INTEGER
      CONSTRAINT FK_ESPECIEANIMAL_GRUPOTAXONOMICO
      REFERENCES GRUPOS_TAXONOMICOS (ID_GRUPO_TAXONOMICO) ON DELETE CASCADE
                                                          ON UPDATE CASCADE,
    ORIGEN              TEXT (32),
    PH_MINIMO           REAL,
    PH_MAXIMO           REAL,
    GH_MINIMO           INTEGER,
    GH_MAXIMO           INTEGER,
    TEMPERATURA_MIN     INTEGER,
    TEMPERATURA_MAX     INTEGER,
    TAMAÑO_ADULTO_CM    INTEGER,
    COMPORTAMIENTO      TEXT,
    DIETA               TEXT,
    NIVEL_ACUARIO       TEXT,
    OBSERVACIONES       TEXT
);

CREATE TABLE ESPECIES_VEGETALES (
    ID_ESPECIE                   INTEGER   PRIMARY KEY AUTOINCREMENT,
    REINO                        TEXT (32) NOT NULL,
    DIVISION                     TEXT (32) NOT NULL,
    CLASE                        TEXT (32) NOT NULL,
    ORDEN                        TEXT (32) NOT NULL,
    FAMILIA                      TEXT (32) NOT NULL,
    GENERO                       TEXT (32) NOT NULL,
    ESPECIE                      TEXT (32) NOT NULL,
    NOMBRE_CIENTIFICO
      [TEXT ]   GENERATED ALWAYS AS (GENERO || ' ' || ESPECIE) STORED
                                           UNIQUE,
    NOMBRE_COMUN                 TEXT (32) NOT NULL,
    ORIGEN                       TEXT (32),
    ID_POSICION_ACUARIO          INTEGER
      CONSTRAINT [FK_ESPECIES VEGETALES_POSICIONACUARIO]
      REFERENCES POSICIONES_ACUARIO (ID_POSICION_ACUARIO) ON DELETE SET NULL
                                                          ON UPDATE CASCADE,
    ID_REQUERIMIENTO_ILUMINACION INTEGER
      CONSTRAINT FK_ESPECIEVEGETAL_REQUERIMIENTOILUMINACION
      REFERENCES REQUERIMIENTOS_ILUMINACION (ID_REQUERIMIENTO_ILUMINACION)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    TEMPERATURA_MIN              INTEGER,
    TEMPERATURA_MAX              INTEGER,
    PH_MINIMO                    REAL,
    PH_MAXIMO                    REAL,
    GH_MINIMO                    INTEGER,
    GH_MAXIMO                    INTEGER,
    ID_REQUERIMIENTO_CO2         INTEGER
      CONSTRAINT FK_ESPECIEVEGETAL_REQUERIMIENTOCO2
      REFERENCES REQUERIMIENTOS_CO2 (ID_REQUERIMIENTO_CO2) ON DELETE SET NULL
                                                           ON UPDATE CASCADE,
    ID_TASA_CRECIMIENTO          INTEGER
      CONSTRAINT FK_ESPECIEVEGETAL_TASACRECIMIENTO
      REFERENCES TASAS_CRECIMIENTO (ID_TASA_CRECIMIENTO) ON DELETE SET NULL
                                                         ON UPDATE CASCADE,
    ID_DIFICULTAD                INTEGER
      CONSTRAINT FK_ESPECIEPLANTA_DIFICULTADPLANTA
      REFERENCES DIFICULTADES_PLANTAS (ID_DIFICULTAD) ON DELETE SET NULL
                                                      ON UPDATE CASCADE,
    OBSERVACIONES                TEXT
);

CREATE TABLE FAUNA_PROYECTO_ACUARIO (
    ID_FAUNA_ACUARIO    INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PROYECTO_ACUARIO INT
      CONSTRAINT FK_FAUNAACUARIO_PROYECTOACUARIO
      REFERENCES PROYECTOS_ACUARIOS (ID_PROYECTO_ACUARIO) ON DELETE CASCADE
                                                          ON UPDATE CASCADE,
    ID_ESPECIE          INT
      CONSTRAINT FK_FAUNAACUARIO_ESPECIESANIMALES
      REFERENCES ESPECIES_ANIMALES (ID_ESPECIE) ON DELETE CASCADE
                                                ON UPDATE CASCADE,
    CANTIDAD            INT,
    FECHA_COMPRA        INT,
    OBSERVACIONES       TEXT
);

CREATE TABLE FILTRO_HISTORICO (
    ID_HISTORICO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_FILTRO    INTEGER
      CONSTRAINT FK_FILTROHISTORICO_FILTRO
      REFERENCES FILTROS (ID_FILTRO) ON DELETE SET NULL
                                     ON UPDATE CASCADE,
    FECHA        INTEGER,
    OBERVACIONES TEXT
);

CREATE TABLE FILTROS (
    ID_FILTRO         INTEGER     PRIMARY KEY AUTOINCREMENT,
    ID_TIPO           INTEGER
      CONSTRAINT FK_TIPOFILTRO_FILTRO
      REFERENCES TIPOS_FILTRO (ID_TIPO) ON DELETE SET NULL
                                        ON UPDATE CASCADE,
    ID_MARCA          INTEGER
      CONSTRAINT FK_FILTRO_MARCACONERCIAL
      REFERENCES MARCAS_COMERCIALES (ID_MARCA) ON DELETE CASCADE
                                               ON UPDATE CASCADE,
    MODELO            TEXT (32),
    NUMERO_SERIE      TEXT (128)  UNIQUE,
    VOLUMEN_ACUARIO   TEXT (11),
    CAUDAL            INTEGER,
    ALTURA_BOMBEO     REAL (3, 1),
    CONSUMO           INTEGER,
    VOLUMEN_FILTRANTE REAL (3, 1),
    ANCHO             INTEGER,
    FONDO             INTEGER,
    ALTO              INTEGER,
    FOTO              BLOB,
    OBSERVACIONES     TEXT
);

CREATE TABLE FLORA_PROYECTO_ACUARIO (
    ID_FLORA_ACUARIO    INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PROYECTO_ACUARIO INT
      CONSTRAINT FK_FLORAACUARIO_PROYECTOACUARIO
      REFERENCES PROYECTOS_ACUARIOS (ID_PROYECTO_ACUARIO) ON DELETE CASCADE
                                                          ON UPDATE CASCADE,
    ID_ESPECIE          INT
      REFERENCES ESPECIES_VEGETALES (ID_ESPECIE) ON DELETE CASCADE
                                                 ON UPDATE CASCADE,
    CANTIDAD            INT,
    FECHA_COMPRA        INT,
    OBSERVACIONES       TEXT
);

CREATE TABLE GRUPOS_TAXONOMICOS (
    ID_GRUPO_TAXONOMICO INTEGER   PRIMARY KEY AUTOINCREMENT,
    GRUPO               TEXT (32) UNIQUE
                                  NOT NULL,
    DESCRIPCION         TEXT
);

CREATE TABLE ILUMINACION (
    ID_ILUMINACION       INTEGER   PRIMARY KEY AUTOINCREMENT,
    ID_ACUARIO           INTEGER,
    ID_TIPO_ILUMINACION  INTEGER
      CONSTRAINT FK_ILUMINACION_TIPOILUMINACION
      REFERENCES TIPOS_ILUMINACION (ID_TIPO_ILUMINACION) ON DELETE SET NULL
                                                         ON UPDATE CASCADE,
    ID_MARCA             INTEGER
      CONSTRAINT FK_ILUMINACION_MARCACOMERCIAL
      REFERENCES MARCAS_COMERCIALES (ID_MARCA) ON DELETE SET NULL
                                               ON UPDATE CASCADE,
    MODELO               TEXT (56),
    POTENCIA_W           REAL,
    FLUJO_LUMINOSO_LM    INTEGER,
    TEMPERATURA_K        INTEGER,
    COLOR                TEXT,
    LONGITUD_CM          REAL,
    ANCHO_CM             REAL,
    ID_TIPO_CONTROL      INTEGER
      CONSTRAINT FK_ILUMINACION_TIPOCONTROLILUMINACION
      REFERENCES TIPOS_CONTROL_ILUMINACION (ID_TIPO_CONTROL) ON DELETE SET NULL
                                                             ON UPDATE CASCADE,
    INTENSIDAD_REGULABLE BOOLEAN   DEFAULT 0,
    ESPECTRO_COMPLETO    BOOLEAN   DEFAULT 0,
    HORAS_DIA            REAL,
    FECHA_INSTALACION    DATE,
    OBSERVACIONES        TEXT,
    FOREIGN KEY (
        ID_ACUARIO
    )
    REFERENCES ACUARIOS (ID_ACUARIO) ON UPDATE CASCADE
                                     ON DELETE SET NULL
);

CREATE TABLE INCIDENCIAS (
    ID_INCIDENCIA    INTEGER    PRIMARY KEY AUTOINCREMENT,
    ID_PROYECTO      INTEGER
      CONSTRAINT FK_INCIDENCIA_PROYECTO
      REFERENCES PROYECTOS (ID_PROYECTO) ON DELETE CASCADE
                                         ON UPDATE CASCADE,
    ID_ACUARIO       INTEGER
      CONSTRAINT FK_INCIDENCIAS_ACUARIO
      REFERENCES ACUARIOS (ID_ACUARIO) ON DELETE SET NULL
                                       ON UPDATE CASCADE,
    FECHA            INTEGER,
    ID_CATEGORIA     INTEGER
      CONSTRAINT FK_INCIDENCIAS_CATEGORIASINCIDENCIA
      REFERENCES CATEGORIAS_INCIDENCIA (ID_CATEGORIA) ON DELETE SET NULL
                                                      ON UPDATE CASCADE,
    ID_SUBCATEGORIA  INTEGER
      CONSTRAINT FK_INCIDENCIA_SUBCATEGORIAINCIDENCIA
      REFERENCES SUBCATEGORIAS_INCIDENCIA (ID_SUBCATEGORIA) ON DELETE SET NULL
                                                            ON UPDATE CASCADE,
    DESCRIPCION      TEXT (128),
    RESUELTA         INTEGER    DEFAULT 0,
    FECHA_RESOLUCION INTEGER,
    OBSERVACIONES    TEXT
);

CREATE TABLE MARCAS_COMERCIALES (
    ID_MARCA      INTEGER    PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT,
    MARCA         TEXT (32)  UNIQUE
                             NOT NULL,
    DIRECCION     TEXT (128),
    COD_POSTAL    TEXT (16),
    POBLACION     TEXT (32),
    PROVINCIA     TEXT (32),
    ID_PAIS       INTEGER,
    OBSERVACIONES TEXT
);

CREATE TABLE MATERIALES_URNA (
    ID_MATERIAL INTEGER   PRIMARY KEY AUTOINCREMENT,
    MATERIAL    TEXT (32) NOT NULL
                          UNIQUE,
    DESCRIPCION TEXT
);

CREATE TABLE PAISES (
    ID_PAIS    INTEGER   PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT,
    PAIS       TEXT (32) UNIQUE,
    CONTINENTE TEXT (32)
);

CREATE TABLE PERIODICIDADES (
    ID_PERIODICIDAD INTEGER   PRIMARY KEY AUTOINCREMENT,
    PERIODICIDAD    TEXT (16) CONSTRAINT IX_PERIODICIDAD UNIQUE
);

CREATE TABLE PLANES_MANTENIMIENTO (
    ID_PLAN_MANTENIMIENTO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ACUARFIO           INTEGER
      CONSTRAINT FK_PANMANTENIMIENTO_ACUARIO
      REFERENCES ACUARIOS (ID_ACUARIO) ON DELETE SET NULL
                                       ON UPDATE CASCADE,
    FECHA_INICIO          INTEGER,
    OBSERVACIONES         TEXT
);

CREATE TABLE POSICIONES_ACUARIO (
    ID_POSICION_ACUARIO INTEGER   PRIMARY KEY AUTOINCREMENT,
    POSICION            TEXT (32) UNIQUE
                                  NOT NULL,
    OBSERVACIONES       TEXT
);

CREATE TABLE PROYECTO_FILTRO (
    ID_PROYECTO_FILTRO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PROYECTO        INTEGER
      CONSTRAINT FK_PROYECTOFILTRO_PROYECTO
      REFERENCES PROYECTOS (ID_PROYECTO) ON DELETE SET NULL
                                         ON UPDATE CASCADE,
    ID_FILTRO          INTEGER CONSTRAINT FK_PROYECTOFILTRO_FILTRO REFERENCES FILTROS (ID_FILTRO) ON DELETE SET NULL
                                                                                                  ON UPDATE CASCADE,
    OBSERVACIONES      TEXT
);

CREATE TABLE PROYECTOS (
    ID_PROYECTO  INTEGER     PRIMARY KEY AUTOINCREMENT,
    ID_USUARIO   INTEGER,
    NOMBRE       TEXT (64),
    FECHA_INICIO INTEGER,
    FECHA_CIERRE INTEGER,
    CERRADO      INTEGER (1),
    DESCRIPCION  TEXT
);

CREATE TABLE PROYECTOS_ACUARIOS (
    ID_PROYECTO_ACUARIO  INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PROYECTO          INTEGER
      CONSTRAINT FK_PROYECTOACUARIO_PROYECTO
      REFERENCES PROYECTOS (ID_PROYECTO) ON DELETE SET NULL
                                         ON UPDATE CASCADE,
    ID_ACUARIO           INTEGER
      CONSTRAINT FK_PROYECTOACUARIO_ACUARIO
      REFERENCES ACUARIOS (ID_ACUARIO) ON DELETE SET NULL
                                       ON UPDATE CASCADE,
    ID_TIPO              INTEGER
      CONSTRAINT FK_PTOYECTOACIARIO_TIPOACUARIO
      REFERENCES TIPOS_ACUARIO (ID_TIPO) ON DELETE SET NULL
                                         ON UPDATE CASCADE,
    VOLUMEN_NETO         INTEGER,
    FECHA_MONTAJE        INTEGER,
    FECHA_INICIO_CICLADO INTEGER,
    FECHA_FIN_CICLADO    INTEGER,
    OBSERVACIONES        TEXT
);

CREATE TABLE PROYECTOS_HISTORICO (
    ID_HISTORICO  INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PROYECTO   INTEGER
      CONSTRAINT FK_PROYECTOHISTORICO_PROYECTO
      REFERENCES PROYECTOS (ID_PROYECTO) ON DELETE SET NULL
                                         ON UPDATE CASCADE,
    FECHA         INTEGER,
    OBSERVACIONES TEXT
);

CREATE TABLE REQUERIMIENTOS_CO2 (
    ID_REQUERIMIENTO_CO2 INTEGER   PRIMARY KEY AUTOINCREMENT,
    REQUERIMIENTO        TEXT (32) UNIQUE
                                   NOT NULL,
    DESCRIPCION          TEXT
);

CREATE TABLE REQUERIMIENTOS_ILUMINACION (
    ID_REQUERIMIENTO_ILUMINACION INTEGER   PRIMARY KEY AUTOINCREMENT,
    REQUERIMIENTO                TEXT (32) UNIQUE
                                           NOT NULL,
    DESCRIPCION                  TEXT
);

CREATE TABLE SUBCATEGORIAS_ACUARIO (
    ID_SUBCATEGORIA_ACUARIO INTEGER   PRIMARY KEY AUTOINCREMENT,
    ID_CATEGORIA_ACUARIO    INTEGER
      CONSTRAINT FK_SUBCATEGORIAACUARIO_CATEGORIAACUARIO
      REFERENCES CATEGORIAS_ACUARIO (ID_CATEGORIA_ACUARIO) ON DELETE CASCADE
                                                           ON UPDATE CASCADE,
    SUBCATEGORIA_ACUARIO    TEXT (32) CONSTRAINT IX_SUBCATEGORIA_ACUARRIO UNIQUE,
    OBSERVACIONES           TEXT,
    CONSTRAINT IX_SUBCATEGORIA UNIQUE (
        ID_CATEGORIA_ACUARIO,
        SUBCATEGORIA_ACUARIO
    )
);

CREATE TABLE SUBCATEGORIAS_INCIDENCIA (
    ID_SUBCATEGORIA     INTEGER   PRIMARY KEY AUTOINCREMENT,
    ID_CATEGORIA        INTEGER   NOT NULL,
    NOMBRE_SUBCATEGORIA TEXT (32) NOT NULL,
    DESCRIPCION         TEXT,
    CONSTRAINT IX_SUBCATEGORIA UNIQUE (
        NOMBRE_SUBCATEGORIA
    )
);

CREATE TABLE SUBTIPO_MANTENIMIENTO (
    ID_SUBTIPO_MANTENIMIENTO INTEGER   PRIMARY KEY AUTOINCREMENT,
    ID_TIPO_MANTENIMIENTO    INTEGER
      REFERENCES TIPO_MANTENIMIENTO (ID_TIPO_MANTENIMIENTO) ON DELETE SET NULL
                                                            ON UPDATE CASCADE,
    SUBTIPO_MANTENIMIENTO    TEXT (32),
    OBSERVACIONES            TEXT,
    CONSTRAINT IX_SUBTIPO_MANTENIMIENTO UNIQUE (
        ID_TIPO_MANTENIMIENTO ASC,
        SUBTIPO_MANTENIMIENTO ASC
    )
);

CREATE TABLE TASAS_CRECIMIENTO (
    ID_TASA_CRECIMIENTO INTEGER   PRIMARY KEY AUTOINCREMENT,
    CRECIMIENTO         TEXT (32) UNIQUE
                                  NOT NULL,
    DESCRIPCION         TEXT
);

CREATE TABLE TIPO_MANTENIMIENTO (
    ID_TIPO_MANTENIMIENTO INTEGER   PRIMARY KEY AUTOINCREMENT,
    TIPO_MANTENIMIENTO    TEXT (32) CONSTRAINT IX_TIPO_MANTENIMIENTO UNIQUE,
    OBSERVACIONES         TEXT
);

CREATE TABLE TIPOS_ACUARIO (
    ID_TIPO                 INTEGER     PRIMARY KEY AUTOINCREMENT,
    ID_CATEGORIA_ACUARIO    INTEGER (1)
      REFERENCES CATEGORIAS_ACUARIO (ID_CATEGORIA_ACUARIO) ON DELETE SET NULL
                                                           ON UPDATE CASCADE,
    ID_SUBCATEGORIA_ACUARIO INTEGER
      CONSTRAINT FK_TIPOACUARIO_SUBCATEGORIAACUARIO
      REFERENCES SUBCATEGORIAS_ACUARIO (ID_SUBCATEGORIA_ACUARIO) ON DELETE SET NULL
                                                                 ON UPDATE CASCADE,
    OBSERVACIONES           TEXT,
    CONSTRAINT IX_TIPO_ACUARIO UNIQUE (
        ID_CATEGORIA_ACUARIO,
        ID_SUBCATEGORIA_ACUARIO
    )
    ON CONFLICT ROLLBACK
);

CREATE TABLE TIPOS_CONTROL_ILUMINACION (
    ID_TIPO_CONTROL INTEGER   PRIMARY KEY AUTOINCREMENT,
    TIPO_CONTROL    TEXT (32) UNIQUE
                              NOT NULL,
    DESCRIPCION     TEXT
);

CREATE TABLE TIPOS_FILTRO (
    ID_TIPO       INTEGER   PRIMARY KEY AUTOINCREMENT,
    TIPO_FILTRO   TEXT (32) CONSTRAINT IX_TIPO_FILTRO UNIQUE,
    OBSERVACIONES TEXT
);

CREATE TABLE TIPOS_ILUMINACION (
    ID_TIPO_ILUMINACION INTEGER   PRIMARY KEY AUTOINCREMENT,
    TIPO                TEXT (32) UNIQUE
                                  NOT NULL,
    DESCRIPCION         TEXT
);

CREATE TABLE USUARIOS (
    ID_USUARIO         INTEGER   PRIMARY KEY AUTOINCREMENT,
    NOMBRE             TEXT (40),
    [PRIMER _APELLIDO] TEXT (40),
    SEGUNDO_APELLIDO   TEXT (40),
    E_MAIL             TEXT (50) UNIQUE,
    CONSTRAINT IX_USUARIO UNIQUE (
        NOMBRE,
        [PRIMER _APELLIDO],
        SEGUNDO_APELLIDO
    )
);