BEGIN TRANSACTION;
CREATE TABLE ACUARIOS (ID_ACUARIO INTEGER PRIMARY KEY AUTOINCREMENT, ID_MARCA INTEGER, MODELO TEXT (64), ANCHURA INTEGER, PROFUNDIDAD INTEGER, ALTURA INTEGER, VOLUMEN_TANQUE INTEGER, VOLUMEN_REAL INTEGER, FECHA_MONTAJE INTEGER, FECHA_INICIO_CICLADO INTEGER, FECHA_FIN_CICLADO INTEGER, DESCRIPCION TEXT);
CREATE TABLE ACUARIO_HISTORICO (ID_HISTORICO INTEGER PRIMARY KEY AUTOINCREMENT, ID_ACUARIO INTEGER CONSTRAINT FK_ACUARIOHISTORICO_ACUARIO REFERENCES ACUARIOS (ID_ACUARIO) ON DELETE SET NULL ON UPDATE CASCADE, FECHA INTEGER, OBSERVACIONES TEXT);
CREATE TABLE CATEGORIAS_PRODUCTO (ID_CATEGORIA_PRODUCTO INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT, CATEGORIA_PRODUCTO TEXT (25) UNIQUE, DESCRIPCION TEXT);
CREATE TABLE COMERCIOS (ID_COMERCIO INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT, COMERCIO TEXT (55) UNIQUE NOT NULL, DIRECCION TEXT (125), COD_POSTAL TEXT (15), POBLACION TEXT (25), PROVINCIA TEXT (25), ID_PAIS INTEGER CONSTRAINT "FK-PAISES_COMECIOS" REFERENCES PAISES (ID_PAIS) ON DELETE SET NULL ON UPDATE CASCADE, OBSERVACIONES TEXT);
CREATE TABLE DETALLES_FACTURA (ID_DETALLE_FACTURA INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT, ID_FACTURA INTEGER CONSTRAINT FK_FACTURA_DETALLEFACTURA REFERENCES FACTURAS (ID_FACTURA) ON DELETE CASCADE ON UPDATE CASCADE, ID_MARCA INTEGER NOT NULL REFERENCES MARCA_PRODUCTO (ID_MARCA) ON DELETE NO ACTION ON UPDATE CASCADE, MODELO TEXT (255) NOT NULL, ID_CATEGORIA_PRODUCTO INTEGER CONSTRAINT FK_CATEGORIAPRODUCTO_DETALLESFACTURA REFERENCES CATEGORIAS_PRODUCTO (ID_CATEGORIA_PRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE, PRECIO REAL (8, 2), DESCRIPCION TEXT);
CREATE TABLE DETALLES_INCIDENCIA (ID_DETALLE_INCIDENCIA INTEGER PRIMARY KEY AUTOINCREMENT, ID_INCIDENCIA INTEGER REFERENCES INCIDENCIAS (ID_INCIDENCIA) ON DELETE CASCADE ON UPDATE CASCADE, FECHA_DETALLE INTEGER, OBSERVACIONES TEXT);
CREATE TABLE FACTURAS (ID_FACTURA INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT, FECHA_COMPRA INTEGER, NUM_FACRURA TEXT (25) UNIQUE, ID_COMERCIO INTEGER, OBERVACIONES TEXT);
CREATE TABLE FILTROS (ID_FILTRO INTEGER PRIMARY KEY AUTOINCREMENT, ID_TIPO INTEGER CONSTRAINT FK_TIPOFILTRO_FILTRO REFERENCES TIPOS_FILTRO (ID_TIPO) ON DELETE SET NULL ON UPDATE CASCADE, ID_MARCA INTEGER CONSTRAINT FK_MARCAPRODUCTO_FILTRO REFERENCES MARCA_PRODUCTO (ID_MARCA) ON DELETE SET NULL ON UPDATE CASCADE, MODELO TEXT (32), NUMERO_SERIE TEXT (128) UNIQUE, VOLUMEN_ACUARIO TEXT (11), CAUDAL INTEGER, ALTURA_BOMBEO REAL (3, 1), CONSUMO INTEGER, VOLUMEN_FILTRANTE REAL (3, 1), ANCHO INTEGER, FONDO INTEGER, ALTO INTEGER, FOTO BLOB, OBSERVACIONES TEXT);
CREATE TABLE FILTRO_HISTORICO (ID_HISTORICO INTEGER PRIMARY KEY AUTOINCREMENT, ID_FILTRO INTEGER CONSTRAINT FK_FILTROHISTORICO_FILTRO REFERENCES FILTROS (ID_FILTRO) ON DELETE SET NULL ON UPDATE CASCADE, FECHA INTEGER, OBERVACIONES TEXT);
CREATE TABLE INCIDENCIAS (ID_INCIDENCIA INTEGER PRIMARY KEY AUTOINCREMENT, ID_PROYECTO INTEGER CONSTRAINT FK_INCIDENCIA_PROYECTO REFERENCES PROYECTOS (ID_PROYECTO) ON DELETE CASCADE ON UPDATE CASCADE, ID_TIPO_INCIDENCIA INTEGER REFERENCES TIPOS_INCIDENCIA (ID_TIPO_INCIDENCIA) ON DELETE SET NULL ON UPDATE CASCADE, FECHA_APERTURA INTEGER, DESCRIPCION_ICIDENCIA TEXT (1024), ESTA_CERRADA INTEGER (1), FECHA_CIERRE INTEGER);
CREATE TABLE MARCA_PRODUCTO (ID_MARCA INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT, MARCA TEXT (25) UNIQUE NOT NULL, DIRECCION TEXT (125), COD_POSTAL TEXT (15), POBLACION TEXT (25), PROVINCIA TEXT (25), ID_PAIS INTEGER CONSTRAINT FK_PAISES_MARCAPRODUCTO REFERENCES PAISES (ID_PAIS) ON DELETE SET NULL ON UPDATE CASCADE, OBSERVACIONES TEXT);
CREATE TABLE PAISES (ID_PAIS INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT, PAIS TEXT (25) UNIQUE, CONTINENTE TEXT (25));
CREATE TABLE PROYECTOS (ID_PROYECTO INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT (64), ID_TIPO INTEGER CONSTRAINT FK_ACUARIO_TIPOACUARIO REFERENCES TIPOS_ACUARIO (ID_TIPO) ON DELETE SET NULL ON UPDATE CASCADE, ID_ACUARIO INTEGER CONSTRAINT FK_PROYECTO_ACUARIO REFERENCES ACUARIOS (ID_ACUARIO) ON DELETE SET NULL ON UPDATE CASCADE, FECHA_INICIO INTEGER, FECHA_CIERRE INTEGER, CERRADO INTEGER (1), DESCRIPCION TEXT);
CREATE TABLE PROYECTO_FILTRO (ID_PROYECTO_FILTRO INTEGER PRIMARY KEY AUTOINCREMENT, ID_PROYECTO INTEGER CONSTRAINT FK_PROYECTOFILTRO_PROYECTO REFERENCES PROYECTOS (ID_PROYECTO) ON DELETE SET NULL ON UPDATE CASCADE, ID_FILTRO INTEGER CONSTRAINT FK_PROYECTOFILTRO_FILTRO REFERENCES FILTROS (ID_FILTRO) ON DELETE SET NULL ON UPDATE CASCADE, OBSERVACIONES TEXT);
CREATE TABLE PROYECTO_HISTORICO (ID_HISTORICO INTEGER PRIMARY KEY AUTOINCREMENT, ID_PROYECTO INTEGER CONSTRAINT FK_PROYECTOHISTORICO_PROYECTO REFERENCES PROYECTOS (ID_PROYECTO) ON DELETE SET NULL ON UPDATE CASCADE, FECHA INTEGER, OBSERVACIONES TEXT);
CREATE TABLE TIPOS_ACUARIO (ID_TIPO INTEGER PRIMARY KEY AUTOINCREMENT, TIPO_ACUARIO TEXT (32) CONSTRAINT IX_TIPO_ACUARIO UNIQUE, DESCRIPCIÓN TEXT);
CREATE TABLE TIPOS_FILTRO (ID_TIPO INTEGER PRIMARY KEY AUTOINCREMENT, TIPO_FILTRO TEXT (32) CONSTRAINT IX_TIPO_FILTRO UNIQUE, OBSERVACIONES TEXT);
INSERT INTO "TIPOS_FILTRO" VALUES(10001,'ESPONJA','IDEAL PARA ACUARIOS PEQUEÑOS O DE CRÍA. FUNCIONA CON AIRE, PROPORCIONANDO FILTRACIÓN MECÁNICA Y BIOLÓGICA SUAVE. SEGURO PARA ALEVINES Y GAMBAS.');
INSERT INTO "TIPOS_FILTRO" VALUES(10002,'INTERNO','SE COLOCA DENTRO DEL ACUARIO, COMBINANDO FILTRACIÓN MECÁNICA Y BIOLÓGICA. FÁCIL DE INSTALAR Y MANTENER. APTO PARA ACUARIOS DE TAMAÑO MEDIO.');
INSERT INTO "TIPOS_FILTRO" VALUES(10003,'CASCADA','CUELGA EN EL BORDE DEL ACUARIO (HOB). OFRECE FILTRACIÓN COMPLETA (MECÁNICA, QUÍMICA Y BIOLÓGICA). POPULAR POR SU RENDIMIENTO Y FÁCIL ACCESO.');
INSERT INTO "TIPOS_FILTRO" VALUES(10004,'EXTERNO','SE SITÚA FUERA DEL ACUARIO. MUY EFICIENTE EN ACUARIOS GRANDES. FILTRA GRANDES VOLÚMENES CON VARIOS MEDIOS FILTRANTES. SILENCIOSO Y VERSÁTIL.');
INSERT INTO "TIPOS_FILTRO" VALUES(10005,'FONDO','INSTALADO BAJO EL SUSTRATO. FILTRA EL AGUA A TRAVÉS DEL FONDO, FAVORECIENDO LA FILTRACIÓN BIOLÓGICA. ÚTIL EN ACUARIOS CON GRAVA FINA.');
INSERT INTO "TIPOS_FILTRO" VALUES(10006,'FILTRO UV','UTILIZA LUZ ULTRAVIOLETA PARA ELIMINAR ALGAS EN SUSPENSIÓN Y MICROORGANISMOS. COMPLEMENTA LA FILTRACIÓN PRINCIPAL. NO AFECTA A LAS BACTERIAS DEL FILTRO BIOLÓGICO.');
INSERT INTO "TIPOS_FILTRO" VALUES(10007,'MOCHILA','COMPACTO Y COLGABLE. SIMILAR AL DE CASCADA, COMBINA VARIOS TIPOS DE FILTRACIÓN. FÁCIL DE INSTALAR Y MANTENER. MUY USADO EN ACUARIOS MEDIANOS.');
INSERT INTO "TIPOS_FILTRO" VALUES(10008,'SUMP / SUMIDERO','SISTEMA EXTERNO UBICADO DEBAJO DEL ACUARIO, GENERALMENTE EN ACUARIOS MARINOS. PERMITE UNA FILTRACIÓN PERSONALIZADA, MAYOR VOLUMEN DE AGUA Y OCULTAR EL EQUIPAMIENTO. MEJORA LA ESTABILIDAD DEL SISTEMA.');
INSERT INTO "TIPOS_FILTRO" VALUES(10009,'EXTERNO1','0SE SITÚA FUERA DEL ACUARIO. MUY EFICIENTE EN ACUARIOS GRANDES. FILTRA GRANDES VOLÚMENES CON VARIOS MEDIOS FILTRANTES. SILENCIOSO Y VERSÁTIL.');
CREATE TABLE TIPOS_INCIDENCIA (ID_TIPO_INCIDENCIA INTEGER PRIMARY KEY AUTOINCREMENT, TIPO_INCIDENCIA TEXT (56) CONSTRAINT IX_TIPO_INCIDENCIA UNIQUE, OBSERVACIONES TEXT);
CREATE UNIQUE INDEX IX_FILTRO ON FILTROS (ID_MARCA, MODELO, NUMERO_sERIE);
CREATE UNIQUE INDEX IX_COMERCIO ON COMERCIOS (COMERCIO ASC);
CREATE UNIQUE INDEX IX_TIPO_ACUARIO ON TIPOS_ACUARIO (TIPO_ACUARIO);
CREATE UNIQUE INDEX IX_NOMBRE ON PROYECTOS (NOMBRE ASC);
CREATE VIEW VISTA_TIPOS_INCIDENCIA AS SELECT  ID_TIPO_INCIDENCIA AS ID,
        ROW_NUMBER() OVER(ORDER BY TIPO_INCIDENCIA) AS NUM,
        TIPO_INCIDENCIA AS TIPO,
        OBSERVACIONES
FROM    TIPOS_INCIDENCIA;
CREATE VIEW VISTA_TIPOS_FILTRO AS SELECT  ID_TIPO AS ID,
        ROW_NUMBER() OVER(ORDER BY ID_TIPO) AS NUM,
        TIPO_FILTRO AS TIPO,
        OBSERVACIONES AS OBSERVACIONES
FROM    TIPOS_FILTRO;
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('TIPOS_FILTRO',10009);
INSERT INTO "sqlite_sequence" VALUES('PAISES',10000);
INSERT INTO "sqlite_sequence" VALUES('MARCA_PRODUCTO',10000);
INSERT INTO "sqlite_sequence" VALUES('CATEGORIAS_PRODUCTO',10000);
INSERT INTO "sqlite_sequence" VALUES('DETALLES_FACTURA',10000);
INSERT INTO "sqlite_sequence" VALUES('PROYECTO_FILTRO',10000);
INSERT INTO "sqlite_sequence" VALUES('FILTROS',10000);
INSERT INTO "sqlite_sequence" VALUES('COMERCIOS',10000);
INSERT INTO "sqlite_sequence" VALUES('ACUARIO_HISTORICO',10000);
INSERT INTO "sqlite_sequence" VALUES('ACUARIOS',10000);
INSERT INTO "sqlite_sequence" VALUES('FACTURAS',10000);
INSERT INTO "sqlite_sequence" VALUES('FILTRO_HISTORICO',10000);
INSERT INTO "sqlite_sequence" VALUES('PROYECTO_HISTORICO',10000);
INSERT INTO "sqlite_sequence" VALUES('TIPOS_INCIDENCIA',10000);
INSERT INTO "sqlite_sequence" VALUES('INCIDENCIAS',10000);
INSERT INTO "sqlite_sequence" VALUES('TIPOS_ACUARIO',10000);
INSERT INTO "sqlite_sequence" VALUES('PROYECTOS',10000);
COMMIT;
